name: Continuous Integration

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Qt and dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-qmake qtbase5-dev qtbase5-dev-tools build-essential cmake ninja-build
        
    - name: Install Qt and dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install qt@5 cmake ninja
        echo "/usr/local/opt/qt@5/bin" >> $GITHUB_PATH
        
    - name: Install Qt (Windows)
      if: matrix.os == 'windows-latest'
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        
    - name: Install build tools (Windows)
      if: matrix.os == 'windows-latest'
      run: choco install cmake ninja
      
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
        
    - name: Build
      run: |
        cd build
        ninja
        
    - name: Verify build artifacts
      run: |
        cd build
        ls -la
        echo "Build completed successfully on ${{ matrix.os }}"